### ISSUE TITLE
データベース試作

### ISSUE THREAD

**Issue by uritake** [nakamura2101187/2023Dev3Early#18]
データベースの試作品置いときます。
修正あるかもです

[データベース案.txt](https://github.com/nakamura2101187/2023Dev3Early/files/11504214/default.txt)

**Comment by uritake** [comment]
[データベース案.txt](https://github.com/nakamura2101187/2023Dev3Early/files/11504268/default.txt)

**Comment by uritake** [comment]
[テキトーにプログラムしてたら不都合な点が出て来たので修正版上げます
[お試しデータベース.txt](https://github.com/nakamura2101187/2023Dev3Early/files/11524740/default.txt)

**Comment by uritake** [comment]
再度改正版です
[データベース改正版.txt](https://github.com/nakamura2101187/2023Dev3Early/files/11526312/default.txt)

**Comment by Sakeyasu** [comment]
了解！
