### ISSUE TITLE
自己紹介

### ISSUE THREAD

**Issue by fu-syoji-t** [nakamura2101187/2023Dev3Early#3]
中村くん、ご招待ありがとう。
issueの練習のためここにみんなの自己紹介をあげてください。
見えてるよとかで大丈夫です。

**Comment by Sakeyasu** [comment]
リーダーの酒見康雅です！
バックエンドの方が得意です
よろしくお願いします

**Comment by oubunsei** [comment]
王です。
よろしくお願いいたします。

**Comment by nakamura2101187** [comment]
中村遥陽です。
頑張りましょう。
よろしくお願いいたします。

**Comment by japanstudent** [comment]
メンバーのふじいです
宜しくお願いします。頑張ってやります？

**Comment by uritake** [comment]
瓜田圭佑です。
バックエンドにしか自信ありません。
皆さんの足を引っ張るかもしれませんが、フォローしてくれると嬉しいです。

**Comment by Sakeyasu** [comment]
### よろしく！
